package com.example.lab4.calculateCurrent.models

data class CalculateCurrentResultModel(
    val Rsh: Double = 0.0,
    val Xsh : Double = 0.0,
    val Zsh: Double = 0.0,
    val Rshmin : Double = 0.0,
    val Xshmin: Double = 0.0,
    val Zshmin: Double = 0.0,
    val I3sh  : Double = 0.0,
    val I2sh  : Double = 0.0,
    val I3shmin : Double = 0.0,
    val I2shmin : Double = 0.0,
    val kpr : Double = 0.0,
    val Rshn : Double = 0.0,
    val Xshn : Double = 0.0,
    val Zshn : Double = 0.0,
    val Rshnmin : Double = 0.0,
    val Xshnmin : Double = 0.0,
    val Zshnmin : Double = 0.0,
    val I3shn : Double = 0.0,
    val I2shn : Double = 0.0,
    val I3shnmin : Double = 0.0,
    val I2shnmin : Double = 0.0,
    val Rl : Double = 0.0,
    val Xl : Double = 0.0,
    val Rcn : Double = 0.0,
    val Xcn : Double = 0.0,
    val Zcn : Double = 0.0,
    val Rcnmin : Double = 0.0,
    val Xcnmin : Double = 0.0,
    val Zcnmin : Double = 0.0,
    val I3ln : Double = 0.0,
    val I2ln : Double = 0.0,
    val I3lnmin : Double = 0.0,
    val I2lnmin: Double = 0.0,
)